
SW0	EQU	P2.0				;SW0_RIGHTPASS 설정
SW1	EQU	P2.1				;SW1_LEFTPASS	설정
SW2	EQU	P2.2				;SW2_STOP	설정
LED		EQU	P1.0

START:
	MOV	R1,#16
	MOV	R2,#16
	MOV	A,#11111110B				;가장 오른쪽 LED ON
	MOV	C,SW2
	JNC	STOP					;SW2 PUSH[0]이면 STOP로
	MOV	C,SW1
	JNC	LPASS					;SW1 PUSH[0]이면 LPASS로
	MOV	A,#01111111B				;가장 왼쪽 LED ON
	MOV	C,SW0
	JNC	RPASS					;SW0 PUSH[0]이면 RPASS로
	JMP	START

LPASS:
	MOV	C,SW0					;SW0 눌렸으면[SW0=0] START로
	JNC	START
	MOV	C,SW2					;SW2 눌렸으면[SW2=0] START로
	JNC	START

	MOV	LED,A
	RL	A					;LED LEFT ROTATION
	XRL	A,#00000001B				;XOR연산해서 A로 이동
	CALL	DELAY
	DJNZ	R2,LPASS				;ROTATION횟수=R2가 끝나지 않으면 LPASS
	CALL	PRINT					;LEFT방향으로 PASS 끝남 표시
	JMP	START

RPASS:
	MOV	C,SW1					;SW1 눌렸으면[SW1=0] START로
	JNC	START
	MOV	C,SW2					;SW2 눌렸으면[SW2=0] START로
	JNC	START
	
	MOV	LED,A
	RR	A					;LED RIGHT ROTATION
	XRL	A,#10000000B				;XOR연산해서 A로 이동
	CALL	DELAY
	DJNZ	R2,RPASS				;ROTATION횟수=R2가 끝나지 않으면 RPASS
	CALL	PRINT					;RIGHT방향으로 PASS 끝남 표시
	JMP	START
STOP:
	MOV	C,SW2					;SW2 눌렸으면[SW2=0] STOP 반복
	JNC	STOP
	MOV	C,SW0					;SW0 눌렸으면[SW0=0] START로
	JNC	START
	MOV	C,SW1					;SW1 눌렸으면[SW0=0] START로
	JNC	START
	RET			
PRINT:						;1회 PASS 완료=FND의 DOT로 표현 
	MOV	P1,#01111111B
	CALL	DELAY
	RET					
DELAY : DJNZ R1, DELAY
RET
